version: "3.9"
services:
  #  Add service for php fpm and nginx
  php-fpm:
    networks:
      backend:
    container_name: ${PROJECT_NAME}_php
    environment:
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: db
      SITE_HOST: ${PROJECT_BASE_URL}

  db:
    image: mariadb:10.2
    networks:
      backend:
    container_name: ${PROJECT_NAME}_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped
#    volumes:
#      - db:/var/lib/mysql

  nginx:
    container_name: "${PROJECT_NAME}_nginx"
    networks:
      backend:
      traefik:
    depends_on:
      - php-fpm
    environment:
      NGINX_BACKEND_HOST: php-fpm
      NGINX_SERVER_NAME: ${PROJECT_BASE_URL}
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_PORT: 80
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

volumes:
    db:

networks:
  backend:
  traefik:
    external: true