version: "3.9"
services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src/:/var/www/html/:cached
  ## Somente descomentar essa linha de não deseja utilizar o traefik
  #    ports:
  #      - ${PROJECT_PORT}:80

  composer:
    image: composer:2.1
    container_name: "${PROJECT_NAME}_composer"
    volumes:
      - ./src/:/app
    working_dir: /app
    command: install --ignore-platform-reqs --no-interaction --optimize-autoloader

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    volumes:
      - ./src/:/var/www/html/:cached

  traefik:
    image: traefik:v2.0
    networks:
      traefik:
    restart: unless-stopped
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - "${PROJECT_PORT}:80"
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
