FROM nginx:1.23.3

COPY docker/templates/nginx/config/nginx.conf /etc/nginx/nginx.conf
COPY docker/templates/nginx/vhost.conf /etc/nginx/templates/vhost.conf.template
COPY docker/templates/nginx/includes/defaults.conf /etc/nginx/defaults.conf
COPY docker/templates/nginx/includes/fastcgi.conf /etc/nginx/fastcgi.conf
COPY docker/templates/nginx/presets/wordpress.conf /etc/nginx/preset.conf
COPY docker/templates/nginx/includes/upstream.php.conf /etc/nginx/templates/upstream.conf.template

RUN rm /etc/nginx/conf.d/default.conf

WORKDIR /var/www/html/web